#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
banner "Remove MyMemo v1 (#765)"

stage "Pin the production state and deployed packages"
cd "$(git rev-parse --show-toplevel)"
repo="$PWD"
export AWS_PROFILE=mymemo AWS_REGION=us-west-2 TF_INPUT=false
export TF_VAR_aws_region=us-west-2 TF_VAR_aws_account_id=637423444544
[[ "$(aws --profile mymemo sts get-caller-identity --query Account --output text)" == "$TF_VAR_aws_account_id" ]]
# Pin the last pre-teardown revision, independent of the operator's current branch.
base=6338550
umask 077
work="$(mktemp -d "${TMPDIR:-/tmp}/mymemo-v1.XXXXXX")"
say "Private evidence directory: $work (contains state and plans; never commit it)."
mkdir -p "$work/strip" "$work/delete"
git archive "$base" infra/terraform | tar -x -C "$work/strip"
# Copy only checked-in configuration, excluding state, generated overlays and caches.
git ls-files infra/terraform | while IFS= read -r file; do
  [[ -f "$file" ]] || continue
  mkdir -p "$work/delete/$(dirname "$file")"
  cp "$file" "$work/delete/$file"
done
strip="$work/strip/infra/terraform"
delete="$work/delete/infra/terraform"
terraform -chdir="$strip" init -lockfile=readonly
terraform -chdir="$strip" show -json > "$work/before.json"
runtime_id="$(jq -er '.values.root_module.resources[] | select(.address == "aws_bedrockagentcore_agent_runtime.agent_runtime") | .values.agent_runtime_id' "$work/before.json")"
runtime_uri="$(aws --profile mymemo bedrock-agentcore-control get-agent-runtime --agent-runtime-id "$runtime_id" --query agentRuntimeArtifact.containerConfiguration.containerUri --output text)"
export TF_VAR_agent_runtime_image_digest="${runtime_uri##*@}"
[[ "$TF_VAR_agent_runtime_image_digest" =~ ^sha256:[0-9a-f]{64}$ ]]
# Fetch the exact currently deployed zip, so teardown cannot redeploy the front.
front_url="$(aws --profile mymemo lambda get-function --function-name mymemo-agent-prod-front --query Code.Location --output text)"
curl --fail --silent --show-error "$front_url" -o "$work/front.zip"
export TF_VAR_front_lambda_package="$work/front.zip"
# filename is an operator-local path, not a deployed setting. Ignore only that
# path during teardown; source_code_hash still detects any changed ZIP bytes.
cat > "$delete/teardown_override.tf" <<'TF'
resource "aws_lambda_function" "front" {
  lifecycle {
    ignore_changes = [filename]
  }
}
TF
export TF_VAR_runtime_image_digest="$(jq -er '.values.outputs.runtime_image_digest.value' "$work/before.json")"
# The targeted strip plan never touches the consumer or ECS, but their required
# variables must still parse. Supply the recorded task images and a zip path.
export TF_VAR_consumer_lambda_package="$work/front.zip"
for pair in chat_api agent_maintenance agentcore_dispatch_publisher; do
  value="$(jq -er --arg address "aws_ecs_task_definition.$pair" '.values.root_module.resources[] | select(.address == $address) | .values.container_definitions | fromjson | .[0].image' "$work/before.json")"
  export "TF_VAR_${pair}_image=$value"
done
e2b_secret="$(jq -er '.values.outputs.e2b_api_key_secret_arn.value' "$work/before.json")"
db_secret="$(jq -er '.values.outputs.agent_database_password_secret_arn.value' "$work/before.json")"
redis_secret="$(jq -er '.values.outputs.redis_url_secret_arn.value' "$work/before.json")"

stage "Strip deletion protection, then apply"
python3 - "$strip" <<'PY'
from pathlib import Path
import sys
root = Path(sys.argv[1])
p = root / "agentcore-queue.tf"
s = p.read_text()
assert "prevent_destroy = true" in s
p.write_text(s.replace("prevent_destroy = true", "prevent_destroy = false"))
p = root / "rds.tf"
s = p.read_text()
assert "skip_final_snapshot     = false" in s
p.write_text(s.replace("var.agent_db_deletion_protection", "false").replace("skip_final_snapshot     = false", "skip_final_snapshot     = true"))
PY
terraform -chdir="$strip" fmt
terraform -chdir="$strip" plan -var-file=prod.tfvars \
  -target=aws_db_instance.agent -target=aws_kms_key.dispatch -out="$work/strip.tfplan"
terraform -chdir="$strip" show -json "$work/strip.tfplan" > "$work/strip.json"
python3 "$repo/scripts/deploy/check_v1_plan.py" strip < "$work/strip.json"
confirm "Apply only the RDS protection/snapshot changes shown above?" || exit 1
terraform -chdir="$strip" apply "$work/strip.tfplan"
[[ "$(aws --profile mymemo rds describe-db-instances --db-instance-identifier mymemo-agent-prod-db --query 'DBInstances[0].DeletionProtection' --output text)" == False ]]

stage "Delete v1 definitions, inspect the deletion-only plan, then apply"
unset TF_VAR_runtime_image_digest TF_VAR_consumer_lambda_package
unset TF_VAR_chat_api_image TF_VAR_agent_maintenance_image TF_VAR_agentcore_dispatch_publisher_image
terraform -chdir="$delete" init -lockfile=readonly
terraform -chdir="$delete" validate
terraform -chdir="$delete" plan -var-file=prod.tfvars -out="$work/delete.tfplan"
terraform -chdir="$delete" show -json "$work/delete.tfplan" > "$work/delete.json"
python3 "$repo/scripts/deploy/check_v1_plan.py" delete < "$work/delete.json"
warn "All v1 data is disposable. This destroys the listed v1 resources without a final DB snapshot."
confirm "Apply this deletion-only plan and schedule the E2B secret for deletion?" || exit 1
terraform -chdir="$delete" apply "$work/delete.tfplan"
# E2B was a data source, so Terraform cannot schedule its deletion. RDS owns
# its password-secret lifecycle; Redis is a Terraform-managed secret.
aws --profile mymemo secretsmanager delete-secret --secret-id "$e2b_secret" --recovery-window-in-days 7

stage "Verify removal and a real Turn"
terraform -chdir="$delete" show -json > "$work/after.json"
python3 - "$work/after.json" "$repo/scripts/deploy/v1-resources.txt" <<'PY'
import json, sys
state = json.load(open(sys.argv[1]))
retired = set(open(sys.argv[2]).read().splitlines())
assert not [r['address'] for r in state['values']['root_module']['resources'] if r['address'].split('[', 1)[0] in retired]
PY
for secret in "$e2b_secret" "$db_secret" "$redis_secret"; do
  say "Verify DeletedDate (or ResourceNotFound for the RDS-owned password): $secret"
  aws --profile mymemo secretsmanager describe-secret --secret-id "$secret" \
    --query '{Name:Name,DeletedDate:DeletedDate}' || {
      warn "Confirm ResourceNotFoundException; any other error is a failed check."
      confirm "Was this the already-removed RDS-owned secret?" || exit 1
    }
done
say "Complete docs/runbooks/v1-teardown.md: unmanaged prototype/dispatch subnets, conditional gateway secret and former dev bucket."
confirm "Have those state/ownership checks and cleanup steps been completed and recorded?" || exit 1
say "Then verify live production resource absence and run a signed Turn with ListDocuments through the Function URL."
say "Record the Turn id, successful KB tool result and unchanged front hash/Runtime digest."
confirm "Have the live inventory and real Turn/KB checks passed and been recorded?" || exit 1
say "Retain the evidence securely. Confirm the roughly USD 80 monthly reduction on the next bill."
finish
