import { BedrockAgentCoreClient, StartCodeInterpreterSessionCommand, InvokeCodeInterpreterCommand, StopCodeInterpreterSessionCommand } from "@aws-sdk/client-bedrock-agentcore";
import { readFileSync } from "node:fs"; import { join } from "node:path";
const env = Object.fromEntries(readFileSync(join(import.meta.dir, "sandbox.env"), "utf8").split("\n").filter((l) => l.includes("=")).map((l) => [l.slice(0, l.indexOf("=")), l.slice(l.indexOf("=") + 1)]));
const CI_ID = env.SBX_ID; const ci = new BedrockAgentCoreClient({ region: "us-west-2" });
const t0 = Date.now(); const log = (...a: unknown[]) => console.log(`[${String(Date.now() - t0).padStart(7)}ms]`, ...a); const ms = (t: number) => Math.round(performance.now() - t);
async function call(sid: string, name: string, args: Record<string, unknown>) { const t = performance.now(); try { const out = await ci.send(new InvokeCodeInterpreterCommand({ codeInterpreterIdentifier: CI_ID, sessionId: sid, name, arguments: args as never })); let r: Record<string, unknown> | null = null; for await (const ev of (out.stream ?? []) as AsyncIterable<Record<string, unknown>>) if (ev.result) r = ev.result as Record<string, unknown>; const sc = (r?.structuredContent ?? {}) as Record<string, unknown>; return { ms: ms(t), ok: !r?.isError, stdout: String(sc.stdout ?? ""), stderr: String(sc.stderr ?? ""), content: (r?.content ?? []) as Array<Record<string, unknown>>, err: "" }; } catch (e) { return { ms: ms(t), ok: false, stdout: "", stderr: "", content: [], err: `${(e as Error).name}: ${(e as Error).message}` }; } }
async function sh(sid: string, c: string, label = c.slice(0, 70)) { const r = await call(sid, "executeCommand", { command: c }); log(`$ ${label} [${r.ms} ms]${r.err ? " " + r.err : ""}`); const o = (r.stdout + (r.stderr ? "\n! " + r.stderr : "")).trim(); if (o) console.log(o.replace(/^/gm, "    ")); return r; }
const s = await ci.send(new StartCodeInterpreterSessionCommand({ codeInterpreterIdentifier: CI_ID, name: "sbx-b", sessionTimeoutSeconds: 900, clientToken: crypto.randomUUID() })); const sid = s.sessionId!; log(`START ${sid}`);
// network characterisation
await sh(sid, "for u in https://s3.us-west-2.amazonaws.com https://s3.amazonaws.com https://s3.eu-west-1.amazonaws.com https://mymemo-agent-prod-artifacts.s3.us-west-2.amazonaws.com/ https://dynamodb.us-west-2.amazonaws.com https://sts.us-west-2.amazonaws.com https://secretsmanager.us-west-2.amazonaws.com https://api.openrouter.ai https://1.1.1.1; do printf '%s -> ' $u; curl -sS -m 5 -o /dev/null -w 'http=%{http_code} ip=%{remote_ip}' $u 2>&1 | head -c 120; echo; done", "which endpoints answer");
await sh(sid, "curl -s -m 5 https://s3.us-west-2.amazonaws.com/ | head -c 300; echo; echo; curl -s -m 5 -X PUT -d hello 'https://s3.us-west-2.amazonaws.com/mymemo-ci-probe-anon-test/x.txt' | head -c 300; echo", "anonymous S3 list + PUT attempt");
await sh(sid, "T=$(curl -s -m 3 -X PUT http://169.254.169.254/latest/api/token -H 'X-metadata-token-ttl-seconds: 60'); echo \"token_len=${#T}\"; curl -s -m 3 -H \"X-metadata-token: $T\" http://169.254.169.254/ | head -c 400; echo; curl -s -m 3 -H \"X-metadata-token: $T\" http://169.254.169.254/latest/meta-data/iam/security-credentials/ | head -c 200; echo; curl -s -m 3 -H \"X-aws-ec2-metadata-token: $T\" http://169.254.169.254/latest/meta-data/ | head -c 200", "MMDS with a token");
await sh(sid, "cat /etc/hosts; grep -v '^#' /run/systemd/resolve/resolv.conf; ip addr | grep -E 'inet |eth'; env | grep -i proxy", "resolver + interfaces");
// readFiles response cap: 10 / 20 / 30 MB; then chunked copy-out
await sh(sid, "mkdir -p ws && head -c 30M /dev/urandom > ws/r30.bin && head -c 20M ws/r30.bin > ws/r20.bin && head -c 10M ws/r30.bin > ws/r10.bin && ls -l ws | awk '{print $5, $9}'", "make 10/20/30 MB files");
for (const mb of [10, 20, 30]) { const r = await call(sid, "readFiles", { paths: [`ws/r${mb}.bin`] }); const blob = (r.content[0]?.resource as Record<string, unknown> | undefined)?.blob; const n = typeof blob === "string" ? Buffer.from(blob, "base64").length : (blob as Uint8Array | undefined)?.length; log(`readFiles ${mb} MB: ${r.ms} ms ok=${r.ok} bytes=${n ?? "n/a"} ${r.err}`); }
await sh(sid, "cd ws && split -b 8m -d r30.bin part- && ls -l part-* | awk '{print $5, $9}'", "split 30 MB into 8 MB parts");
let t = performance.now(); let total = 0; for (const p of ["part-00", "part-01", "part-02", "part-03"]) { const r = await call(sid, "readFiles", { paths: [`ws/${p}`] }); const blob = (r.content[0]?.resource as Record<string, unknown> | undefined)?.blob; total += typeof blob === "string" ? Buffer.from(blob, "base64").length : (blob as Uint8Array | undefined)?.length ?? 0; } log(`chunked copy-out of 30 MB in 4 reads: ${ms(t)} ms, ${total} bytes`);
const multi = await call(sid, "readFiles", { paths: ["ws/part-00", "ws/part-01"] }); log(`readFiles two 8 MB parts in one call: ${multi.ms} ms ok=${multi.ok} ${multi.err}`);
await ci.send(new StopCodeInterpreterSessionCommand({ codeInterpreterIdentifier: CI_ID, sessionId: sid })); log("stopped");
